services:
  - type: web
    name: visual-product-matcher-app
    env: java
    rootDir: visual-product-matcher
    buildCommand: "mvn clean install -U"
    startCommand: "java -jar target/visual-product-matcher-1.0-SNAPSHOT.jar"
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: visual-matcher-db
          property: connectionString
