services:
  # A Web Service for your Spring Boot application
  - type: web
    name: visual-product-matcher-app
    # THE FIX: The incorrect 'runtime: java' line has been removed.
    # Render will now auto-detect it as a Java project.
    rootDir: visual-product-matcher
    buildCommand: "mvn clean install -U"
    startCommand: "java -jar target/visual-product-matcher-1.0-SNAPSHOT.jar"
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: visual-matcher-db # Make sure this matches your Render DB name
          property: connectionString
